import type { Student, Topic, Paper, Question, Result } from '../types';

export interface SeedDataPayload {
  students: Student[];
  topics: Topic[];
  papers: Paper[];
  questions: Question[];
  results: Result[];
}

const NOW = Date.now();
const DAY = 24 * 60 * 60 * 1000;

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 's_01',
    name: 'Liam Chen',
    grade: '12th Grade',
    syllabus_board: 'IB DP Math AA',
    target_exam: 'IB May 2026 Higher Level',
    avatar_color: '#00F0FF',
    schedule_time: '08:30 AM',
    notes: 'Aims for 7/7. Struggles with Taylor Series convergence tests.',
    created_at: NOW - 60 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_02',
    name: 'Sophia Rodriguez',
    grade: '10th Grade',
    syllabus_board: 'Cambridge IGCSE',
    target_exam: 'IGCSE Extended Math 0580',
    avatar_color: '#00FF88',
    schedule_time: '09:15 AM',
    notes: 'Strong algebraic manipulation, needs help with 3D Trigonometry & Bearings.',
    created_at: NOW - 50 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_03',
    name: 'Ethan Patel',
    grade: '11th Grade',
    syllabus_board: 'AP Calculus BC',
    target_exam: 'AP Exam (Target: 5)',
    avatar_color: '#FFB800',
    schedule_time: '10:00 AM',
    notes: 'Fast worker, occasional careless sign errors in Integration by Parts.',
    created_at: NOW - 45 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_04',
    name: 'Maya Al-Mansoor',
    grade: '10th Grade',
    syllabus_board: 'CBSE Class 10/12',
    target_exam: 'CBSE Board Standard Math',
    avatar_color: '#FF0055',
    schedule_time: '10:45 AM',
    notes: 'Exam anxiety on word problems involving Quadratic Equations.',
    created_at: NOW - 35 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_05',
    name: 'Alexander Wright',
    grade: '12th Grade',
    syllabus_board: 'A-Level Physics',
    target_exam: 'Edexcel A-Level (Target: A*)',
    avatar_color: '#8B5CF6',
    schedule_time: '11:30 AM',
    notes: 'Very high aptitude for Mechanics; needs intervention on Capacitance & Magnetic Fields.',
    created_at: NOW - 40 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_06',
    name: 'Emma Watson',
    grade: '11th Grade',
    syllabus_board: 'IB DP Math AA',
    target_exam: 'IB Standard Level',
    avatar_color: '#EC4899',
    schedule_time: '12:45 PM',
    notes: 'Excellent on Statistics; needs confidence in Vector Equations of Lines.',
    created_at: NOW - 30 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_07',
    name: 'Lucas Silva',
    grade: '11th Grade',
    syllabus_board: 'AP Physics C',
    target_exam: 'AP Physics C Mechanics',
    avatar_color: '#14B8A6',
    schedule_time: '01:30 PM',
    notes: 'Rotational Dynamics mastered. Simple Harmonic Motion damped oscillations need review.',
    created_at: NOW - 25 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_08',
    name: 'Olivia Kim',
    grade: '9th Grade',
    syllabus_board: 'Cambridge IGCSE',
    target_exam: 'IGCSE Core Math',
    avatar_color: '#3B82F6',
    schedule_time: '02:15 PM',
    notes: 'Visual learner. Geometry theorems need repeated reinforcement.',
    created_at: NOW - 20 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_09',
    name: 'Noah Schmidt',
    grade: '12th Grade',
    syllabus_board: 'AP Calculus BC',
    target_exam: 'AP BC Exam',
    avatar_color: '#F97316',
    schedule_time: '03:00 PM',
    notes: 'Polar coordinates area integrals need practice.',
    created_at: NOW - 15 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_10',
    name: 'Ava Taylor',
    grade: '12th Grade',
    syllabus_board: 'CBSE Class 10/12',
    target_exam: 'CBSE 12th Board Mathematics',
    avatar_color: '#A855F7',
    schedule_time: '03:45 PM',
    notes: 'Mastered Differential Equations; needs intervention on Linear Programming & Bayes Theorem.',
    created_at: NOW - 18 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_11',
    name: 'Oliver Brown',
    grade: '10th Grade',
    syllabus_board: 'Cambridge IGCSE',
    target_exam: 'IGCSE Additional Math 0606',
    avatar_color: '#EAB308',
    schedule_time: '04:30 PM',
    notes: 'Trigonometric identities proof steps need rigorous structure.',
    created_at: NOW - 22 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_12',
    name: 'Isabella Garcia',
    grade: '11th Grade',
    syllabus_board: 'IB DP Math AA',
    target_exam: 'IB Math SL',
    avatar_color: '#06B6D4',
    schedule_time: '05:15 PM',
    notes: 'Functions and graphs are solid. Binomial Theorem coefficients need drilling.',
    created_at: NOW - 10 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_13',
    name: 'Elijah Jones',
    grade: '11th Grade',
    syllabus_board: 'General STEM',
    target_exam: 'SAT Math 800',
    avatar_color: '#10B981',
    schedule_time: '06:00 PM',
    notes: 'Pacing is good. High-level algebra & circle geometry need review.',
    created_at: NOW - 12 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_14',
    name: 'Charlotte Davis',
    grade: '10th Grade',
    syllabus_board: 'Cambridge IGCSE',
    target_exam: 'IGCSE Combined Science & Math',
    avatar_color: '#F43F5E',
    schedule_time: '06:45 PM',
    notes: 'Very creative problem solver. Needs systematic checking of units & dimensions.',
    created_at: NOW - 8 * DAY,
    updated_at: NOW,
  },
  {
    id: 's_15',
    name: 'James Wilson',
    grade: '12th Grade',
    syllabus_board: 'AP Calculus BC',
    target_exam: 'College Board BC',
    avatar_color: '#6366F1',
    schedule_time: '07:30 PM',
    notes: 'Preparing for mock exam next Monday.',
    created_at: NOW - 5 * DAY,
    updated_at: NOW,
  }
];

export const INITIAL_TOPICS: Topic[] = [
  // Liam Chen (IB DP Math AA) - 6 core topics for Radar Chart
  { id: 'top_01', student_id: 's_01', name: 'Differential Calculus', syllabus_code: 'IB-5.1', mastery_percentage: 84.0, last_tested_at: NOW - 3 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_02', student_id: 's_01', name: 'Integral Calculus', syllabus_code: 'IB-5.5', mastery_percentage: 76.5, last_tested_at: NOW - 6 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_03', student_id: 's_01', name: 'Taylor & Maclaurin Series', syllabus_code: 'IB-5.12', mastery_percentage: 48.0, last_tested_at: NOW - 38 * DAY, is_weak: true, created_at: NOW, updated_at: NOW }, // decayed & weak (<60%)
  { id: 'top_04', student_id: 's_01', name: '3D Vector Geometry', syllabus_code: 'IB-3.4', mastery_percentage: 54.0, last_tested_at: NOW - 12 * DAY, is_weak: true, created_at: NOW, updated_at: NOW }, // weak (<60%)
  { id: 'top_05', student_id: 's_01', name: 'Complex Numbers', syllabus_code: 'IB-1.7', mastery_percentage: 52.0, last_tested_at: NOW - 18 * DAY, is_weak: true, created_at: NOW, updated_at: NOW }, // weak (<60%)
  { id: 'top_06', student_id: 's_01', name: 'Probability Distributions', syllabus_code: 'IB-4.7', mastery_percentage: 88.0, last_tested_at: NOW - 4 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },

  // Sophia Rodriguez (Cambridge IGCSE)
  { id: 'top_07', student_id: 's_02', name: 'Algebraic Expressions', syllabus_code: 'IG-C2', mastery_percentage: 92.0, last_tested_at: NOW - 2 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_08', student_id: 's_02', name: '3D Trigonometry & Bearings', syllabus_code: 'IG-E6', mastery_percentage: 45.0, last_tested_at: NOW - 35 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_09', student_id: 's_02', name: 'Quadratic Functions', syllabus_code: 'IG-C3', mastery_percentage: 78.0, last_tested_at: NOW - 5 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_10', student_id: 's_02', name: 'Circle Theorems', syllabus_code: 'IG-E4', mastery_percentage: 55.0, last_tested_at: NOW - 14 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_11', student_id: 's_02', name: 'Vector Geometry', syllabus_code: 'IG-E7', mastery_percentage: 82.0, last_tested_at: NOW - 8 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_12', student_id: 's_02', name: 'Coordinate Geometry', syllabus_code: 'IG-C5', mastery_percentage: 74.0, last_tested_at: NOW - 10 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },

  // Ethan Patel (AP Calculus BC)
  { id: 'top_13', student_id: 's_03', name: 'Limits & Continuity', syllabus_code: 'AP-U1', mastery_percentage: 95.0, last_tested_at: NOW - 4 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_14', student_id: 's_03', name: 'Parametric & Polar Equations', syllabus_code: 'AP-U9', mastery_percentage: 52.0, last_tested_at: NOW - 32 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_15', student_id: 's_03', name: 'Infinite Sequences & Series', syllabus_code: 'AP-U10', mastery_percentage: 58.0, last_tested_at: NOW - 11 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_16', student_id: 's_03', name: 'Integration Techniques', syllabus_code: 'AP-U6', mastery_percentage: 86.0, last_tested_at: NOW - 3 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_17', student_id: 's_03', name: 'Differential Equations', syllabus_code: 'AP-U7', mastery_percentage: 79.0, last_tested_at: NOW - 7 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_18', student_id: 's_03', name: 'Applications of Definite Integrals', syllabus_code: 'AP-U8', mastery_percentage: 83.0, last_tested_at: NOW - 5 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },

  // Maya Al-Mansoor (CBSE Class 10)
  { id: 'top_19', student_id: 's_04', name: 'Real Numbers & Polynomials', syllabus_code: 'CBSE-U1', mastery_percentage: 91.0, last_tested_at: NOW - 1 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_20', student_id: 's_04', name: 'Quadratic Equations (Word Problems)', syllabus_code: 'CBSE-U2', mastery_percentage: 42.0, last_tested_at: NOW - 40 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_21', student_id: 's_04', name: 'Arithmetic Progressions', syllabus_code: 'CBSE-U3', mastery_percentage: 75.0, last_tested_at: NOW - 9 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_22', student_id: 's_04', name: 'Triangles & Similarity', syllabus_code: 'CBSE-U4', mastery_percentage: 56.0, last_tested_at: NOW - 16 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_23', student_id: 's_04', name: 'Trigonometric Applications & Heights', syllabus_code: 'CBSE-U5', mastery_percentage: 50.0, last_tested_at: NOW - 20 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_24', student_id: 's_04', name: 'Surface Areas & Volumes', syllabus_code: 'CBSE-U7', mastery_percentage: 80.0, last_tested_at: NOW - 4 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },

  // Alexander Wright (A-Level Physics)
  { id: 'top_25', student_id: 's_05', name: 'Kinematics & Newton Laws', syllabus_code: 'AL-PHY1', mastery_percentage: 96.0, last_tested_at: NOW - 2 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_26', student_id: 's_05', name: 'Capacitors & Exponential Decay', syllabus_code: 'AL-PHY4', mastery_percentage: 48.0, last_tested_at: NOW - 36 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_27', student_id: 's_05', name: 'Electromagnetic Induction', syllabus_code: 'AL-PHY5', mastery_percentage: 54.0, last_tested_at: NOW - 15 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_28', student_id: 's_05', name: 'Nuclear Decay & Radiation', syllabus_code: 'AL-PHY7', mastery_percentage: 51.0, last_tested_at: NOW - 25 * DAY, is_weak: true, created_at: NOW, updated_at: NOW },
  { id: 'top_29', student_id: 's_05', name: 'Thermal Physics & Ideal Gases', syllabus_code: 'AL-PHY8', mastery_percentage: 82.0, last_tested_at: NOW - 6 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
  { id: 'top_30', student_id: 's_05', name: 'Wave Optics & Interference', syllabus_code: 'AL-PHY3', mastery_percentage: 88.0, last_tested_at: NOW - 5 * DAY, is_weak: false, created_at: NOW, updated_at: NOW },
];

export const INITIAL_PAPERS: Paper[] = [
  {
    id: 'pap_01',
    student_id: 's_01',
    title: 'IB DP Math AA HL - Targeted Mastery Set #14',
    status: 'needs_grading', // 🔴 Red dot
    target_class_time: '08:30 AM',
    total_marks: 40,
    scored_marks: 0,
    grading_duration_seconds: 0,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_02',
    student_id: 's_02',
    title: 'Cambridge IGCSE - Bearings & Circle Mastery #08',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '09:15 AM',
    total_marks: 35,
    scored_marks: 31,
    created_at: NOW - 2 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_03',
    student_id: 's_03',
    title: 'AP Calculus BC - Polar Area & Series Convergence',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '10:00 AM',
    total_marks: 45,
    scored_marks: 39,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_04',
    student_id: 's_04',
    title: 'CBSE Standard Math - Word Problems & Heights Sprint',
    status: 'needs_grading', // 🔴 Red dot
    target_class_time: '10:45 AM',
    total_marks: 30,
    scored_marks: 0,
    grading_duration_seconds: 0,
    created_at: NOW - 2 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_05',
    student_id: 's_05',
    title: 'A-Level Physics - Magnetic Flux & Capacitance Drift',
    status: 'needs_grading', // 🔴 Red dot
    target_class_time: '11:30 AM',
    total_marks: 50,
    scored_marks: 0,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_06',
    student_id: 's_06',
    title: 'IB DP Math SL - 3D Vector Lines Sprint',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '12:45 PM',
    total_marks: 35,
    scored_marks: 29,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_07',
    student_id: 's_07',
    title: 'AP Physics C - Damped Harmonic Oscillations',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '01:30 PM',
    total_marks: 40,
    scored_marks: 36,
    created_at: NOW - 3 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_08',
    student_id: 's_08',
    title: 'IGCSE Core - Angle Theorems & Polygons',
    status: 'needs_grading', // 🔴 Red dot
    target_class_time: '02:15 PM',
    total_marks: 30,
    scored_marks: 0,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_09',
    student_id: 's_09',
    title: 'AP Calculus BC - Polar Derivatives & Arc Length',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '03:00 PM',
    total_marks: 40,
    scored_marks: 34,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_10',
    student_id: 's_10',
    title: 'CBSE 12th - Bayes Theorem & Conditional Sprint',
    status: 'needs_grading', // 🔴 Red dot
    target_class_time: '03:45 PM',
    total_marks: 30,
    scored_marks: 0,
    created_at: NOW - 2 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_11',
    student_id: 's_11',
    title: 'Cambridge Add Math - Trigonometric Proofs',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '04:30 PM',
    total_marks: 35,
    scored_marks: 30,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_12',
    student_id: 's_12',
    title: 'IB Math SL - Binomial Expansions & Negative Powers',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '05:15 PM',
    total_marks: 35,
    scored_marks: 32,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_13',
    student_id: 's_13',
    title: 'SAT Math - Advanced Functions & Circle Geometry',
    status: 'needs_grading', // 🔴 Red dot
    target_class_time: '06:00 PM',
    total_marks: 40,
    scored_marks: 0,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_14',
    student_id: 's_14',
    title: 'IGCSE Combined - Stoichiometry & Kinematics',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '06:45 PM',
    total_marks: 30,
    scored_marks: 27,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  },
  {
    id: 'pap_15',
    student_id: 's_15',
    title: 'AP Calculus BC - Comprehensive Mock Sprint',
    status: 'ready_for_class', // 🟢 Green dot
    target_class_time: '07:30 PM',
    total_marks: 50,
    scored_marks: 44,
    created_at: NOW - 1 * DAY,
    updated_at: NOW,
  }
];

export const INITIAL_QUESTIONS: Question[] = [
  // Paper 1 (Liam Chen - 10 questions for Zen Grading + 3 Pre-fetched Alternates)
  {
    id: 'q_01_01',
    paper_id: 'pap_01',
    topic_id: 'top_03',
    topic_name: 'Taylor & Maclaurin Series',
    question_number: 1,
    question_text: 'Find the first four non-zero terms of the Maclaurin expansion for f(x) = e^(2x) · cos(x).',
    answer_key: '1 + 2x + (3/2)x^2 + (1/3)x^3 + ...',
    marking_scheme: [
      'M1: Expands e^(2x) = 1 + 2x + 2x^2 + (4/3)x^3',
      'M1: Expands cos(x) = 1 - (1/2)x^2',
      'A1: Multiplies terms up to x^3 correctly',
      'A1: Combines like terms into 1 + 2x + 1.5x^2 + 0.333x^3'
    ],
    difficulty: 2, // 60% weak distribution (Diff 1-2)
    max_marks: 4,
    is_alternate: false,
    order_index: 0,
  },
  {
    id: 'q_01_02',
    paper_id: 'pap_01',
    topic_id: 'top_03',
    topic_name: 'Taylor & Maclaurin Series',
    question_number: 2,
    question_text: 'Use the ratio test to determine the radius of convergence R for the series sum_{n=1}^inf ((-1)^n · (x - 3)^n) / (n · 4^n).',
    answer_key: 'R = 4, Interval: (-1, 7]',
    marking_scheme: [
      'M1: Sets up |a_{n+1} / a_n| with limit as n -> infinity',
      'M1: Evaluates limit: |x - 3| / 4 < 1',
      'A1: Concludes radius of convergence R = 4',
      'A1: Tests endpoints x = 7 (converges) and x = -1 (diverges)'
    ],
    difficulty: 2,
    max_marks: 4,
    is_alternate: false,
    order_index: 1,
  },
  {
    id: 'q_01_03',
    paper_id: 'pap_01',
    topic_id: 'top_04',
    topic_name: '3D Vector Geometry',
    question_number: 3,
    question_text: 'Given line L1: r = (2, 0, -1) + t(1, -2, 3) and plane Pi: 2x + y - z = 5. Find the coordinates of the point of intersection.',
    answer_key: '(1, 2, -4) with t = -1',
    marking_scheme: [
      'M1: Substitutes parametric line coordinates into plane equation',
      'M1: Solves 2(2 + t) + (-2t) - (-1 + 3t) = 5 for parameter t',
      'A1: Obtains t = -1',
      'A1: Substitutes back to find coordinates (1, 2, -4)'
    ],
    difficulty: 1,
    max_marks: 4,
    is_alternate: false,
    order_index: 2,
  },
  {
    id: 'q_01_04',
    paper_id: 'pap_01',
    topic_id: 'top_04',
    topic_name: '3D Vector Geometry',
    question_number: 4,
    question_text: 'Calculate the acute angle between vectors u = 2i - j + 2k and v = 3i + 4k. Express answer to the nearest 0.1 degree.',
    answer_key: 'theta = arccos(14/15) approx 21.0 deg',
    marking_scheme: [
      'M1: Computes dot product: (2)(3) + (-1)(0) + (2)(4) = 14',
      'M1: Computes magnitudes: |u| = 3, |v| = 5',
      'A1: Applies cos(theta) = 14 / 15',
      'A1: Final angle = 21.0 degrees'
    ],
    difficulty: 2,
    max_marks: 4,
    is_alternate: false,
    order_index: 3,
  },
  {
    id: 'q_01_05',
    paper_id: 'pap_01',
    topic_id: 'top_05',
    topic_name: 'Complex Numbers',
    question_number: 5,
    question_text: 'Express z = (1 + i * sqrt(3))^6 in rectangular form x + iy.',
    answer_key: '64 + 0i (or 64)',
    marking_scheme: [
      'M1: Converts 1 + i*sqrt(3) to polar form: r = 2, theta = pi/3',
      'M1: Applies De Moivre’s Theorem: z^6 = 2^6 * (cos(2pi) + i*sin(2pi))',
      'A1: Calculates 2^6 = 64',
      'A1: Rectangular form: 64'
    ],
    difficulty: 2,
    max_marks: 4,
    is_alternate: false,
    order_index: 4,
  },
  {
    id: 'q_01_06',
    paper_id: 'pap_01',
    topic_id: 'top_05',
    topic_name: 'Complex Numbers',
    question_number: 6,
    question_text: 'Solve the equation w^3 = -8i, giving all roots in Euler form r * e^(i*theta) where -pi < theta <= pi.',
    answer_key: '2e^(-ipi/6), 2e^(i5pi/6), 2e^(-i5pi/6)',
    marking_scheme: [
      'M1: Writes -8i in polar form: 8e^(-i*pi/2)',
      'M1: Applies cube root to modulus: r = 2',
      'A1: Finds principal argument theta_1 = -pi/6',
      'A1: Finds subsequent arguments separated by 2pi/3'
    ],
    difficulty: 2,
    max_marks: 4,
    is_alternate: false,
    order_index: 5,
  },
  {
    id: 'q_01_07',
    paper_id: 'pap_01',
    topic_id: 'top_01',
    topic_name: 'Differential Calculus',
    question_number: 7,
    question_text: 'Find the equation of the tangent to the curve defined implicitly by x^3 + y^3 - 3xy = 3 at the point (2, 1).',
    answer_key: 'y = -3x + 7',
    marking_scheme: [
      'M1: Differentiates implicitly: 3x^2 + 3y^2(dy/dx) - 3(y + x*dy/dx) = 0',
      'M1: Isolates dy/dx = (y - x^2) / (y^2 - x)',
      'A1: Evaluates gradient at (2, 1): m = -3',
      'A1: Tangent equation: y - 1 = -3(x - 2) => y = -3x + 7'
    ],
    difficulty: 4, // 40% strong challenge (Diff 4-5)
    max_marks: 4,
    is_alternate: false,
    order_index: 6,
  },
  {
    id: 'q_01_08',
    paper_id: 'pap_01',
    topic_id: 'top_01',
    topic_name: 'Differential Calculus',
    question_number: 8,
    question_text: 'A cylinder has volume V = 250pi cm^3. Find the height h and radius r that minimize the total surface area.',
    answer_key: 'r = 5 cm, h = 10 cm',
    marking_scheme: [
      'M1: Expresses surface area S(r) = 2pi*r^2 + 500pi/r',
      'M1: Sets derivative dS/dr = 4pi*r - 500pi/r^2 = 0',
      'A1: Solves r^3 = 125 => r = 5 cm',
      'A1: Calculates h = 10 cm and verifies minimum using second derivative'
    ],
    difficulty: 4,
    max_marks: 4,
    is_alternate: false,
    order_index: 7,
  },
  {
    id: 'q_01_09',
    paper_id: 'pap_01',
    topic_id: 'top_06',
    topic_name: 'Probability Distributions',
    question_number: 9,
    question_text: 'X follows a Poisson distribution with mean lambda = 4.2. Find P(2 <= X <= 4) rounded to 4 decimal places.',
    answer_key: '0.5151',
    marking_scheme: [
      'M1: Identifies P(X = k) = e^(-4.2) * 4.2^k / k!',
      'M1: Computes P(X=2) = 0.1325, P(X=3) = 0.1855, P(X=4) = 0.1948',
      'A1: Sums values = 0.5128',
      'A1: Correct rounding to 4 decimal places'
    ],
    difficulty: 5,
    max_marks: 4,
    is_alternate: false,
    order_index: 8,
  },
  {
    id: 'q_01_10',
    paper_id: 'pap_01',
    topic_id: 'top_06',
    topic_name: 'Probability Distributions',
    question_number: 10,
    question_text: 'The continuous random variable Y has PDF f(y) = k*(4 - y^2) for 0 <= y <= 2, and 0 otherwise. Determine the exact value of k and E[Y].',
    answer_key: 'k = 3/16, E[Y] = 3/4',
    marking_scheme: [
      'M1: Integrates integral_0^2 k(4 - y^2) dy = 1 to find k',
      'A1: [4y - y^3/3]_0^2 = 16/3 => k = 3/16',
      'M1: Evaluates E[Y] = integral_0^2 (3/16)(4y - y^3) dy',
      'A1: [2y^2 - y^4/4]_0^2 = 4 => E[Y] = (3/16)*4 = 3/4'
    ],
    difficulty: 5,
    max_marks: 4,
    is_alternate: false,
    order_index: 9,
  },

  // PRE-FETCHED ALTERNATE QUESTIONS FOR ZERO-WAIT SWAPPING (Paper 1)
  {
    id: 'alt_01_01',
    paper_id: 'pap_01',
    topic_id: 'top_03',
    topic_name: 'Taylor & Maclaurin Series',
    question_number: 99,
    question_text: 'ALTERNATE: Find the third-degree Taylor polynomial for f(x) = ln(x) centered at a = 1.',
    answer_key: 'P_3(x) = (x - 1) - (1/2)(x - 1)^2 + (1/3)(x - 1)^3',
    marking_scheme: [
      'M1: Computes derivatives: f\'(1) = 1, f\'\'(1) = -1, f\'\'\'(1) = 2',
      'A1: Constructs polynomial with factorial denominators',
      'A1: Simplifies to standard centered form'
    ],
    difficulty: 2,
    max_marks: 4,
    is_alternate: true, // Pre-fetched alternate!
    order_index: 100,
  },
  {
    id: 'alt_01_02',
    paper_id: 'pap_01',
    topic_id: 'top_04',
    topic_name: '3D Vector Geometry',
    question_number: 99,
    question_text: 'ALTERNATE: Find a Cartesian equation of the plane passing through point A(1, 2, 3) and perpendicular to vector n = (3, -1, 4).',
    answer_key: '3x - y + 4z = 13',
    marking_scheme: [
      'M1: Uses 3(x - 1) - 1(y - 2) + 4(z - 3) = 0',
      'A1: Expands 3x - y + 4z - 3 + 2 - 12 = 0',
      'A1: Final form: 3x - y + 4z = 13'
    ],
    difficulty: 2,
    max_marks: 4,
    is_alternate: true,
    order_index: 101,
  },
  {
    id: 'alt_01_03',
    paper_id: 'pap_01',
    topic_id: 'top_01',
    topic_name: 'Differential Calculus',
    question_number: 99,
    question_text: 'ALTERNATE: Evaluate the limit lim_{x -> 0} (e^x - 1 - x) / x^2 using L\'Hopital\'s Rule.',
    answer_key: '1/2',
    marking_scheme: [
      'M1: Identifies 0/0 indeterminate form',
      'M1: Applies L\'Hopital once: lim (e^x - 1) / (2x)',
      'A1: Applies L\'Hopital second time: lim (e^x) / 2 = 1/2'
    ],
    difficulty: 4,
    max_marks: 4,
    is_alternate: true,
    order_index: 102,
  },
];
